global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "inference_stats"
    scrape_interval: 10s
    scrape_timeout: 10s
    honor_labels: false
    honor_timestamps: true
    metrics_path: /metrics
    static_configs:
      - targets: ["fastapi:8000"]

  - job_name: "node-exporter"
    scrape_interval: 10s
    scrape_timeout: 10s
    honor_labels: false
    honor_timestamps: true
    metrics_path: /metrics
    static_configs:
      - targets: ["node-exporter:9100"]

groups:
  - name: clipsat.rules
    interval: 30s
    rules:
      - record: clipsat:req_rate_5m
        expr: sum(rate(inference_requests_total[5m]))

      - record: clipsat:error_rate_5m
        expr: sum(rate(inference_errors_total[5m]))
          /
          sum(rate(inference_requests_total[5m]))

      - record: clipsat:cache_hit_ratio_5m
        expr: sum(rate(model_cache_hit_total[5m]))
          /
          (
            sum(rate(model_cache_hit_total[5m]))
            +
            sum(rate(model_cache_miss_total[5m]))
          )
