{
 "title": "CLIPSAT Inference Monitoring",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "model", "label": "model", "query": "1, 2, 3, 4, production" },
   { "name": "endpoint", "label": "endpoint", "query": "/predict, /predict/batch" }
  ]
 },
 "panels": [
  { "title": "System Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage In Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage In Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"node-exporter:9100\"} - node_memory_MemAvailable_bytes{instance=\"node-exporter:9100\"} - node_memory_Cached_bytes{instance=\"node-exporter:9100\"} - node_memory_Buffers_bytes{instance=\"node-exporter:9100\"}",
     "legendFormat": "Total used"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=\"node-exporter:9100\"}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"node-exporter:9100\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"node-exporter:9100\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"node-exporter:9100\"} - node_memory_MemFree_bytes{instance=\"node-exporter:9100\"} - node_memory_Cached_bytes{instance=\"node-exporter:9100\"} - node_memory_Buffers_bytes{instance=\"node-exporter:9100\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"node-exporter:9100\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=\"node-exporter:9100\"}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"node-exporter:9100\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Disk Usage In Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{device=\"/dev/mapper/data-root\"} - node_filesystem_free_bytes{device=\"/dev/mapper/data-root\"}) / node_filesystem_size_bytes{device=\"/dev/mapper/data-root\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  { "title": "Traffic Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Model Request / Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(inference_requests_total) by (model)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Endpoint Requests / Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "sum(inference_requests_total) by (endpoint)",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Page Views",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\n  page_views_total{endpoint=\"/ui/inference_ui\"},\n  \"page\",\n  \"Inference UI\",\n  \"endpoint\",\n  \".*\"\n)",
     "legendFormat": "{{page}}"
    },
    {
     "expr": "label_replace(\n  page_views_total{endpoint=\"/ui/model_comparison\"},\n  \"page\",\n  \"Model Comparison\",\n  \"endpoint\",\n  \".*\"\n)",
     "legendFormat": "{{page}}"
    },
    {
     "expr": "label_replace(\n  page_views_total{endpoint=\"/ui/training_ui\"},\n  \"page\",\n  \"Training UI\",\n  \"endpoint\",\n  \".*\"\n)",
     "legendFormat": "{{page}}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "sum(rate(inference_errors_total[5m])) /\nsum(rate(inference_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Invalid Payload Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum(rate(invalid_payload_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Latency Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Inference Latency (P95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(inference_latency_seconds_bucket[5m])) by (le))",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Preproc. Latency (P95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,\nsum(rate(preprocessing_latency_seconds_bucket[5m])) by (le))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  { "title": "Infrastructure Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Model Cache Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "sum(rate(model_cache_hit_total[5m]))\n/\n(sum(rate(model_cache_hit_total[5m]))\n+\nsum(rate(model_cache_miss_total[5m])))",
     "legendFormat": "Model Cache Efficiency"
    }
   ]
  },
  {
   "title": "Model Load Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,sum(rate(model_load_latency_seconds_bucket[5m])) by (le))",
     "legendFormat": "Model Load Latency"
    }
   ]
  },
  {
   "title": "Request Payload Size",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(inference_request_bytes_bucket[5m])) by (le, endpoint))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Response Payload Size",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,sum(rate(inference_response_bytes_bucket[5m])) by (le, endpoint))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Inflight Requests",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "inference_inflight", "legendFormat": "{{endpoint}}" }
   ]
  },
  {
   "title": "Model Load Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "targets": [
    {
     "expr": "increase(model_load_errors_total[1h])",
     "legendFormat": "{{model}}"
    }
   ]
  },
  { "title": "Prediction Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 } },
  {
   "title": "Prediction Distribution (model: $model, endpoint: $endpoint)",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "targets": [
    {
     "expr": "sum(rate(prediction_distribution_bucket{model=\"$model\", endpoint=\"$endpoint\"}[5m])) by (le)",
     "legendFormat": "{Prediction Probabilities}"
    }
   ]
  },
  {
   "title": "Batch Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(batch_size_bucket[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Missing Feature Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
   "targets": [
    {
     "expr": "rate(input_feature_missing_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prediction Errors Per Model",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
   "targets": [
    {
     "expr": "rate(model_prediction_errors_total[5m])",
     "legendFormat": "{{model}}"
    }
   ]
  }
 ]
}